import java.applet.Applet;
import java.awt.*;
public class RegForm extends Applet
{
	Label lblRoll,lblName,lblGender,lblCourse,lblPaper,lblSession,lblCollege,lblDob;
	TextField txtRoll,txtName,txtSession,txtDob;
	Button btnSave,btnReset,btnClose;
	Choice ch;
	Choice ch1;
	Font f,f1;
	Checkbox ckMale,ckFemale,ckOther;
	CheckboxGroup cbg;
	Image logo;
	public void init()
	{
		setLayout(null);
		logo=getImage(getDocumentBase(),"logo.png");
		f=new Font("Script MT Bold",Font.BOLD,40);
		f1=new Font("Algerian",Font.BOLD,30);
		//Label lbl= new Label("Roll No:");
		//Font f=new Font("Serif",Font.BOLD,29);
		//lbl.setFont(f);
		lblRoll=new Label("Roll No:");
		lblName=new Label("Name:");
		lblGender=new Label("Gender:");
		lblCourse=new Label("Course:");
		lblPaper=new Label("Papers:");
		lblSession=new Label("Session:");
		lblCollege=new Label("College:");
		lblDob=new Label("Date of Birth:");
		txtRoll=new TextField(5);
		txtName=new TextField(20);
		txtSession=new TextField(15);
		txtDob=new TextField(10);
		btnSave=new Button("Save");
		btnReset=new Button("Reset");
		btnClose=new Button("Close");
		cbg=new CheckboxGroup();
		ckMale=new Checkbox("Male",cbg,true);
		ckFemale=new Checkbox("Female",cbg,false);
		ckOther=new Checkbox("Other",cbg,false);
		ch=new Choice();
		ch.add("BCA");
		ch.add("MCA");
		ch.add("BBA");
		ch.add("MBA");
		ch.add("BIT");
		ch.add("Biotech");
		ch.add("OMSP");
		add(ch);
		ch1=new Choice();
		ch1.add("T.N.B. College");
		ch1.add("Marwari College");
		ch1.add("S.M. College");
		ch1.add("B.N. College");
		ch1.add("Other");
		add(ch1);
		add(lblPaper);
		Checkbox cxFandamental,cxClanguage,cxMsoffice,cxPython,cxC,cxAccounting,cxOFM,cxManagement,cxIT,cxTally;
		cxFandamental=new Checkbox("Fandamental");
		cxClanguage=new Checkbox("C language");
		cxMsoffice=new Checkbox("Ms-Office");
		cxPython=new Checkbox("Python");
		cxC= new Checkbox("C++");
		cxAccounting=new Checkbox("Accounting");
		cxOFM=new Checkbox("Office Management");
		cxManagement=new Checkbox("Management");
		cxIT=new Checkbox("Infoemation Tech.");
		cxTally=new Checkbox("Tally");
		add(cxFandamental);
		add(cxClanguage);
		add(cxMsoffice);
		add(cxPython);
		add(cxC);
		add(cxAccounting);
		add(cxOFM);
		add(cxManagement);
		add(cxIT);
		add(cxTally);
		add(lblRoll);
		add(lblName);
		add(lblGender);
		add(lblSession);
		add(lblDob);
		add(txtRoll);
		add(txtName);
		add(txtSession);
		add(txtDob);
		add(btnSave);
		add(btnReset);
		add(btnClose);
		add(ckMale);
		add(ckFemale);
		add(ckOther);
		add(lblCourse);
		add(lblSession);
		add(txtSession);
		add(lblCollege);
		add(lblDob);
		add(txtDob);
		lblRoll.setBounds(10,150,80,30);
		lblName.setBounds(10,200,80,30);
		lblGender.setBounds(10,250,80,30);
		lblCourse.setBounds(10,300,80,30);
		lblPaper.setBounds(10,350,80,30);
		lblSession.setBounds(10,600,80,30);
		lblCollege.setBounds(10,650,80,30);
		lblDob.setBounds(10,700,80,30);
		txtDob.setBounds(100,700,150,30);
		ch1.setBounds(100,650,150,30);
		txtRoll.setBounds(100,150,150,30);
		txtName.setBounds(100,200,150,30);
		txtSession.setBounds(100,600,150,30);
		ckMale.setBounds(100,250,100,25);
		ckFemale.setBounds(200,250,100,25);
		ckOther.setBounds(300,250,100,25);
		ch.setBounds(100,305,80,30);
		cxFandamental.setBounds(100,360,80,15);
		cxClanguage.setBounds(100,400,80,15);
		cxMsoffice.setBounds(100,450,80,15);
		cxPython.setBounds(100,500,80,15);
		cxC.setBounds(100,550,80,15);
		cxAccounting.setBounds(300,360,100,15);
		cxOFM.setBounds(300,400,120,15);
		cxManagement.setBounds(300,450,110,15);
		cxIT.setBounds(300,500,120,15);
		cxTally.setBounds(300,550,100,15);
		btnSave.setBounds(100,800,120,60);
		btnReset.setBounds(300,800,120,60);
		btnClose.setBounds(500,800,120,60);
	}
	public void paint(Graphics g)
	{
		g.setFont(f);
		g.setFont(f1);
		g.drawImage(logo,5,35,this);
		g.drawString("T.M.Bhagalpur University,Bhagalpur",120,30);
		g.drawString("Student Registration Form",180,80);
	}
}
//<applet code="RegForm.class" height="1000" width="800"></Applet>